appName: hello-world
serviceName: hello-world
configName: hello-world-config

image:
  artifactory: blr-artifactory.cloud.health.ge.com
  nodeType: LoadBalancer
  repository: 474054470595.dkr.ecr.us-east-1.amazonaws.com/hello-world
  imageName: hello-world
  tag: latest

global:
  namespace: edison-ai
  nodeType: LoadBalancer
  iso: true
  registry_base_url: 474054470595.dkr.ecr.us-east-1.amazonaws.com


internalPort: 80
replicas: 1
imagePullPolicy: IfNotPresent


resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

configMap:
  qidoURL: "http://a98a2c9cc5ab64dcc8c20de09b14ab94-1563977660.us-east-1.elb.amazonaws.com:30043"
  workflowURL: "http://a7075b72e61e54686a5a1384d2946116-2086856152.us-east-1.elb.amazonaws.com:8080"
  imagingURL: "http://a79622b36627f4630925f4b9f5199cbd-592421661.us-east-1.elb.amazonaws.com:4000"
  imagingHost: "a3a58a8d60c0f47cabb949411c52391a-2063558325.us-east-1.elb.amazonaws.com:8080"

